export enum ErrorCode {
  INVALID_CREDENTIALS = 1,
  INVALID_GOOGLE_TOKEN = 2,
  APPLICATION_REQUEST_ERROR = 3,
  INVALID_GENDER = 4,
  NO_PLAYER = 5,
  NO_MATCH = 6,
  APPLICATION_TEAM_FULL = 7,
  APPLICATION_NO_EXIST = 8,
  APPLICATION_CLOSED = 9,
  APPLICATION_MATCH_CLOSED = 10,
  CATEGORY_INVALID = 11
}
